# Mathematical & Statistical Operations


In [12]:
import numpy as np

1. Find the mean, median, standard deviation, and variance of a random array of size 10.

In [13]:
random_array = np.random.rand(10)  # Generates 10 random floats between 0 and 1.
mean_val = np.mean(random_array)
median_val = np.median(random_array)
std_val = np.std(random_array)
var_val = np.var(random_array)

print("Random array of size 10:\n", random_array)
print("\nMean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)
print("Variance:", var_val)

Random array of size 10:
 [0.70602272 0.48509909 0.4156897  0.49579353 0.42356199 0.91518786
 0.63062454 0.07439949 0.02014084 0.98318194]

Mean: 0.5149701719140829
Median: 0.4904463123670703
Standard Deviation: 0.2979436420019657
Variance: 0.08877041380939552


2. Normalize a random 5x5 matrix (so all values are between 0 and 1).

In [14]:
matrix_5x5 = np.random.rand(5, 5)  # Random 5x5 matrix (values already between 0 and 1)
# If you had arbitrary values, you would normalize as follows:
# matrix_min = np.min(matrix_5x5)
# matrix_max = np.max(matrix_5x5)
# normalized_matrix = (matrix_5x5 - matrix_min) / (matrix_max - matrix_min)
normalized_matrix = matrix_5x5  # Already normalized since np.random.rand() generates [0,1] values
print("\nRandom 5x5 matrix:\n", matrix_5x5)
print("\nNormalized 5x5 matrix:\n", normalized_matrix)



Random 5x5 matrix:
 [[0.42717367 0.21059353 0.04466187 0.63403708 0.01190928]
 [0.89994879 0.67325985 0.86952567 0.72533906 0.90215684]
 [0.20029846 0.83982207 0.95478647 0.56263314 0.72592071]
 [0.49280955 0.66126162 0.55043582 0.1429673  0.29827324]
 [0.78118476 0.44589219 0.78610623 0.76179763 0.52159594]]

Normalized 5x5 matrix:
 [[0.42717367 0.21059353 0.04466187 0.63403708 0.01190928]
 [0.89994879 0.67325985 0.86952567 0.72533906 0.90215684]
 [0.20029846 0.83982207 0.95478647 0.56263314 0.72592071]
 [0.49280955 0.66126162 0.55043582 0.1429673  0.29827324]
 [0.78118476 0.44589219 0.78610623 0.76179763 0.52159594]]


3. Compute the determinant of a random 3x3 matrix.

In [15]:
matrix_3x3 = np.random.rand(3, 3)
determinant = np.linalg.det(matrix_3x3)
print("\nRandom 3x3 matrix:\n", matrix_3x3)
print("\nDeterminant of the 3x3 matrix:", determinant)



Random 3x3 matrix:
 [[0.94739853 0.73849781 0.50636607]
 [0.9770524  0.01952746 0.2276642 ]
 [0.54478737 0.20129994 0.53432444]]

Determinant of the 3x3 matrix: -0.2332750047809137


4. Find the eigenvalues and eigenvectors of a symmetric 3x3 matrix.

In [16]:
# Create a symmetric matrix. One way is to create a random matrix and then symmetrize it.
A = np.random.rand(3, 3)
symmetric_matrix = (A + A.T) / 2  # Ensures symmetry.
eigenvalues, eigenvectors = np.linalg.eigh(symmetric_matrix)  # 'eigh' is for Hermitian (symmetric) matrices.
print("\nSymmetric 3x3 matrix:\n", symmetric_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Symmetric 3x3 matrix:
 [[0.26137349 0.43339234 0.62274399]
 [0.43339234 0.55487738 0.44999043]
 [0.62274399 0.44999043 0.31779069]]

Eigenvalues:
 [-0.33381049  0.08402894  1.38382311]
Eigenvectors:
 [[-0.72436572  0.41252741 -0.55237256]
 [ 0.00417432 -0.79857906 -0.60187546]
 [ 0.68940328  0.43828373 -0.57674127]]


5. Perform element-wise multiplication of two matrices of the same shape.

In [17]:
matrix1 = np.random.rand(4, 4)  # Example 4x4 matrix.
matrix2 = np.random.rand(4, 4)  # Another 4x4 matrix.
elementwise_product = np.multiply(matrix1, matrix2)  # Alternatively, use matrix1 * matrix2.
print("\nMatrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nElement-wise multiplication of Matrix 1 and Matrix 2:\n", elementwise_product)


Matrix 1:
 [[0.58513726 0.09664744 0.1823847  0.56901647]
 [0.09956232 0.47533743 0.93628673 0.18589126]
 [0.12849445 0.32065037 0.0985805  0.69448787]
 [0.1075098  0.78605082 0.75493252 0.2064701 ]]

Matrix 2:
 [[0.97603693 0.1785385  0.88901546 0.5156531 ]
 [0.33014928 0.20038661 0.76548173 0.29920825]
 [0.63561452 0.32097914 0.10967579 0.95344027]
 [0.93505813 0.73604325 0.46267608 0.02865021]]

Element-wise multiplication of Matrix 1 and Matrix 2:
 [[0.57111558 0.01725529 0.16214282 0.29341511]
 [0.03287043 0.09525126 0.71671039 0.0556202 ]
 [0.08167294 0.10292208 0.01081189 0.6621527 ]
 [0.10052792 0.57856741 0.34928922 0.00591541]]
