# Advanced Indexing & Fancy Indexing




In [1]:
import numpy as np


1. Given a = np.array([10, 20, 30, 40, 50]), select elements at indices [1, 3].



In [2]:
a = np.array([10, 20, 30, 40, 50])
selected_elements = a[[1, 3]]
print("Selected elements at indices [1, 3]:", selected_elements)

Selected elements at indices [1, 3]: [20 40]



Create a 6x6 matrix and fill its diagonal with numbers from 1 to 6.

In [3]:
matrix_6x6 = np.zeros((6, 6), dtype=int)
np.fill_diagonal(matrix_6x6, np.arange(1, 7))
print("\n6x6 matrix with diagonal filled from 1 to 6:")
print(matrix_6x6)


6x6 matrix with diagonal filled from 1 to 6:
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


Create an 8x8 checkerboard pattern (0s and 1s).

In [4]:
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print("\n8x8 Checkerboard pattern (0s and 1s):")
print(checkerboard)


8x8 Checkerboard pattern (0s and 1s):
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
