#  Broadcasting & Performance

In [1]:
import numpy as np
import time

1.  Broadcasting: Adding two arrays.

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])
broadcast_sum = arr1 + arr2
print("Broadcasted addition of arr1 and arr2:\n", broadcast_sum)

Broadcasted addition of arr1 and arr2:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


2. Subtract the row mean from each row in a 3x4 matrix.

In [3]:
matrix = np.random.rand(3, 4)
row_means = np.mean(matrix, axis=1, keepdims=True)
centered_matrix = matrix - row_means
print("\nOriginal 3x4 matrix:\n", matrix)
print("\nRow means:\n", row_means)
print("\nMatrix after subtracting row means:\n", centered_matrix)


Original 3x4 matrix:
 [[0.46164266 0.90462139 0.94890201 0.08948277]
 [0.67564927 0.55086506 0.9453881  0.56647592]
 [0.28264631 0.55838215 0.97604703 0.24897076]]

Row means:
 [[0.60116221]
 [0.68459459]
 [0.51651156]]

Matrix after subtracting row means:
 [[-0.13951955  0.30345919  0.3477398  -0.51167944]
 [-0.00894532 -0.13372952  0.26079351 -0.11811867]
 [-0.23386525  0.04187059  0.45953547 -0.26754081]]


3. Performance: Multiply a 1000x1000 random matrix with its transpose.

In [4]:
large_matrix = np.random.rand(1000, 1000)
start_time = time.time()
result = np.dot(large_matrix, large_matrix.T)
end_time = time.time()
print("\nTime taken to multiply 1000x1000 matrix with its transpose: {:.5f} seconds".format(end_time - start_time))


Time taken to multiply 1000x1000 matrix with its transpose: 0.07182 seconds


4. Rotate a 5x5 matrix 90 degrees clockwise without using a loop.

In [5]:
import numpy as np

# Create a sample 5x5 matrix.
matrix = np.arange(1, 26).reshape(5, 5)
print("Original Matrix:")
print(matrix)

# Rotate the matrix 90 degrees clockwise.
# Method 1: Using numpy.rot90 with a negative k.
rotated_matrix = np.rot90(matrix, k=-1)

# Alternatively, you can transpose and then reverse the rows:
# rotated_matrix = matrix.T[::-1, :]

print("\nRotated Matrix (90 degrees clockwise):")
print(rotated_matrix)


Original Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Rotated Matrix (90 degrees clockwise):
[[21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]
 [25 20 15 10  5]]
