# 2. Sales Data Analysis

In [1]:
import numpy as np

i:  Data Setup

In [3]:

# Create a 7x3 sales data array, where each entry is a random integer between 50 and 500.
sales_data = np.random.randint(50, 500, (7, 3))
print("Sales Data (Rows = Days, Columns = Products):")
print(sales_data)


Sales Data (Rows = Days, Columns = Products):
[[360 280 144]
 [228 284 170]
 [151 440 433]
 [493 343 335]
 [332 123 442]
 [347 488 287]
 [461 229 174]]


ii: Calculate Total Sales for Each Product

In [4]:
# Sum sales over rows (each product's sales over all days)
total_sales_per_product = np.sum(sales_data, axis=0)
print("Total sales for each product:", total_sales_per_product)


Total sales for each product: [2372 2187 1985]


iii:  Identify the Day with the Highest Total Sales

In [5]:
# Sum sales across products for each day
daily_totals = np.sum(sales_data, axis=1)
print("Total sales per day:", daily_totals)

# Identify the day (index) with the highest total sales
max_day_index = np.argmax(daily_totals)
print("Day with the highest total sales (0-indexed):", max_day_index)
print("Day with the highest total sales (1-indexed):", max_day_index + 1)


Total sales per day: [ 784  682 1024 1171  897 1122  864]
Day with the highest total sales (0-indexed): 3
Day with the highest total sales (1-indexed): 4


iv: Compute the Average Daily Sales Across All Products

In [6]:
# Calculate the average of all sales data entries
average_daily_sales = np.mean(sales_data)
print("Average daily sales across all products:", average_daily_sales)


Average daily sales across all products: 311.6190476190476
