#  Array Operations & Manipulations

1. Reverse an array (first element becomes last).

In [3]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])
reversed_array = original_array[::-1]
print("Original array:", original_array)
print("Reversed array:", reversed_array)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


Create a 1D array of 50 evenly spaced values between 2 and 10.

In [4]:
evenly_spaced = np.linspace(2, 10, 50)
print("\n1D array of 50 evenly spaced values between 2 and 10:\n", evenly_spaced)



1D array of 50 evenly spaced values between 2 and 10:
 [ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]


Reshape the array [1,2,3,4,5,6,7,8,9] into a 3x3 matrix.

In [5]:
arr_1_to_9 = np.array([1,2,3,4,5,6,7,8,9])
matrix_3x3 = arr_1_to_9.reshape(3, 3)
print("\n3x3 matrix from the array [1,2,3,4,5,6,7,8,9]:\n", matrix_3x3)


3x3 matrix from the array [1,2,3,4,5,6,7,8,9]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Replace all elements greater than 5 in an array with 0.

In [6]:
modified_array = original_array.copy()
modified_array[modified_array > 5] = 0  # No effect here since original_array has max 5.
# Let's create a new array that has some values > 5:
sample_array = np.array([2, 6, 4, 8, 3, 7, 5])
sample_array[sample_array > 5] = 0
print("\nModified array with elements greater than 5 replaced with 0:\n", sample_array)


Modified array with elements greater than 5 replaced with 0:
 [2 0 4 0 3 0 5]


Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [7]:
A = np.arange(1, 16).reshape(5, 3)  # 5x3 matrix with values 1 to 15.
B = np.arange(1, 7).reshape(3, 2)    # 3x2 matrix with values 1 to 6.
dot_product = np.dot(A, B)
print("\nMatrix A (5x3):\n", A)
print("Matrix B (3x2):\n", B)
print("Dot product (5x2 matrix):\n", dot_product)


Matrix A (5x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Matrix B (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Dot product (5x2 matrix):
 [[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


Flatten a multidimensional array.

In [8]:
multidim_array = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = multidim_array.flatten()
print("\nOriginal multidimensional array:\n", multidim_array)
print("Flattened array:\n", flattened_array)


Original multidimensional array:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]
