Create an array of 10 zeros.

In [1]:
import numpy as np

zeros_array = np.zeros(10)

print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create an array of 10 fives.

In [2]:
array_of_fives = np.full(10, 5)
print("Array of 10 fives:\n", array_of_fives)

Array of 10 fives:
 [5 5 5 5 5 5 5 5 5 5]


Create an array of integers from 10 to 50.

In [3]:
integers_10_to_50 = np.arange(10, 51)
print("\nArray of integers from 10 to 50:\n", integers_10_to_50)


Array of integers from 10 to 50:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create a 3x3 matrix with values ranging from 0 to 8.

In [4]:
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values 0 to 8:\n", matrix_0_to_8)


3x3 Matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 5x5 identity matrix.

In [5]:
identity_matrix = np.eye(5)
print("\n5x5 Identity matrix:\n", identity_matrix)


5x5 Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Generate a random number between 0 and 1.

In [6]:
random_number = np.random.rand()
print("\nRandom number between 0 and 1:\n", random_number)


Random number between 0 and 1:
 0.3980996809536056


Generate an array of 25 random numbers sampled from a standard normal distribution (mean=0, std=1).

In [7]:
random_normal_array = np.random.randn(25)  # mean=0, std=1 by default
print("\nArray of 25 random numbers from a standard normal distribution:\n", random_normal_array)


Array of 25 random numbers from a standard normal distribution:
 [ 0.37865663 -0.86252815  1.83845201  0.69987363 -0.11691659  0.94329615
 -0.18122246 -0.0674412   0.17704685 -1.0281018   0.34052176  0.91160128
  1.4192707   1.91723014 -0.31861838 -0.24985323 -0.40059136 -0.35252824
  0.42796455  0.84921034  0.49642556  0.79567218  0.504235   -0.77651689
  1.00826428]


Given array: numbers 1 to 25 reshaped into a 5x5 matrix.

In [8]:
arr = np.arange(1, 26).reshape(5, 5)
print("Original array:\n", arr)


Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


 Extract the submatrix:
    We need the submatrix:
    [[12 13 14 15]
     [17 18 19 20]
     [22 23 24 25]]
    These values come from rows 2 to 4 (0-indexed rows 2, 3, 4) and columns 1 to 4.

In [9]:
submatrix = arr[2:5, 1:5]
print("\nExtracted submatrix:\n", submatrix)



Extracted submatrix:
 [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Get the number 20.

In [10]:
number_20 = arr[3, 4]
print("\nThe number 20 is:", number_20)


The number 20 is: 20


Get the column from 2 to 22 in steps of 5.

In [11]:
column = arr[:, 1]
print("\nColumn with values from 2 to 22 in steps of 5:\n", column)


Column with values from 2 to 22 in steps of 5:
 [ 2  7 12 17 22]
